## Librerías
Por lo general, Anaconda tiene instalado diferentes paquetes o librerías de manera predeterminada, para comprobar los paquetes instalados, pueden utilizar el siguiente código.
```python
!conda list
```

In [ ]:
!conda list

### NumPy
NumPy es un paquete fundamental a la hora de realizar análisis de datos. La mayoría de librerías y programas de minería de datos, computación científica y machine learning se basan en este paquete, debido a la eficiencia computacional y de memoria que utiliza para realizar operaciones en los datos y el manejo de arreglos multidimensionales.<br>

Para poder ver la documentación de NumPy, lo pueden averiguar de la <a href ='https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html' >Página Oficial</a>.<br> O también la pueden consultar a través del Menú *Help > NumPy Reference* <br> <br>
Sin embargo, leer toda la documentación y aprenderse todas las funciones puede ser un poco tedioso. Para eso existen una página de resumen o <a href = 'https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf'>*Cheat Sheet*</a>. <br> <br>
Al ser un código que no ha sido desarrollado por nostros, hay que importarlo.

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]],
 dtype = float)
print(c[1])
print(c[1][1])
print(c[1][1][1])

#### Funciones Iniciales
Así como se puede definir un ```array``` con datos, también existen formas de inicializar una matriz de forma predeterminada como por ejemplo:

In [ ]:
np.zeros((3,4))

In [ ]:
np.ones((2,3,4),dtype=np.int16) 

In [ ]:
d = np.arange(10,25,5) 
d

In [ ]:
np.linspace(0,2,9) 

In [ ]:
e = np.full((2,2),7) 
e

In [ ]:
f = np.eye(2) 
f

In [ ]:
ran = np.random.random((2,2)) 
ran

In [ ]:
np.empty((3,2)) 

#### Operaciones básicas
Lo bueno de utilizar las matrices es que comparten sus propiedades matemáticas, por eso se pueden multiplicar y sumar por un escalar o por otra matriz que cumpla las propiedades

In [ ]:
#se puede utilizar operaciones igual que en Python
print("8F + E")
print(8*f + e)

#O se puede utilizar funciones
print("La matriz A + B")
print(np.add(a,b) )
print("La matriz A * B")
print(np.multiply(a,b) )
print("El producto punto entre E y F")
print(e.dot(f))

#### Otras Funciones
También existen otras funciones importantes que se pueden utilizar en las matrices. Recuerden que si quieren ver todas las funciones pueden ir a la página oficila de NumPy.

In [ ]:
#Suma de toda la matriz
print(a.sum())
#Máximo según filas
print(b.max(axis=1))
#Media por columnas
print(b.mean(axis=0))
#Coef. de correlacion
print(np.corrcoef(ran))

### Ejercicio #3
Cree una función la cual le permita elevar la matriz a un número $n$. Ambos valores deben ser recibidos por parámetros y en caso tal que no defina el número $n$ a elevar, devuelva la misma matriz.

```python
mat =  [[1 2 3]
        [3 1 2]
        [2 3 1]]

elevarMatriz(mat,3)
[[ 1  8 27]
 [27  1  8]
 [ 8 27  1]]

elevarMatriz(mat)
[[1 2 3]
 [3 1 2]
 [2 3 1]]
```

### Ejercicio #4
Cree una función que le permita normalizar una matriz por columnas

Recuerde que normalizar es aplicar la función:
$$\frac{X-{\mu}}{\sigma}$$

Donde: 
- $X$: elemento de la lista.
- $\mu$: media poblacional.
- $\sigma$: varianza poblacional.

**Ej:**
```python
mat1 =  [[1 2]
        [2 1]]

centrarMatriz(mat1)
[[-0.5,  0.5]
 [ 0.5, -0.5]]

mat2 =  [6.87080258 2.2235544 ]
        [2.10842914 2.73036457]
        [5.47449245 6.85607747]
        [2.05994198 5.88935416]
        [6.39454097 3.6013204 ]

centrarMatriz(mat2)
[[ 2.28916115, -2.03657979]
 [-2.47321229, -1.52976963]
 [ 0.89285103,  2.59594327]
 [-2.52169944,  1.62921996]
 [ 1.81289954, -0.6588138 ]]
```

### Pandas
Pandas es una librería open-sorce la cual permite el uso de estructura de datos y herramientas de análisis reconocida a nivel mundial.<br>

Para poder ver la documentación de Pandas, lo pueden averiguar de la <a href ='https://pandas.pydata.org/pandas-docs/stable/?v=20191021133224' >Página Oficial</a>.<br> O también la pueden consultar a través del Menú *Help > pandas Reference* <br> <br>
Así como NumPy, existe una página de resumen o <a href = 'http://datacamp-community-prod.s3.amazonaws.com/dbed353d-2757-4617-8206-8767ab379ab3'>*Cheat Sheet*</a> que permite resumir las funcionalidades de la librería. 

#### Lectura de Archivos
Al ser código externo, para poder utilizarlo es necesario importar la librería. Para este ejemplo vamos a leer un archivo en csv conocido como la base de datos **Iris** ubicado en Internet.

In [ ]:
import pandas as pd
df = pd.read_csv("https://forge.scilab.org/index.php/p/rdataset/source/file/master/csv/datasets/iris.csv")
#Observar los primeros datos del DataFrame
df.head()

#### Atributos básicos
Existen algunos atributos asociados al DataFrame que se acaba de crear que se puede utilizar para visualizar los datos como por ejemplo: <br>
```columns```: Define el nombre de las columnas del dataFrame. <br>
```index```: Define el nombre de las filas del dataFrame. <br>
```dtypes```: Define el tipo de dato en cada columna. <br>
```size```: Determina la cantidad de datos del dataFrame. <br>
```shape```: Devuelve un arreglo con las dimensiones del dataFrame. <br>

In [ ]:
df.columns

In [ ]:
df.index

In [ ]:
df.dtypes

In [ ]:
df.size

In [ ]:
df.shape

#### Funciones Básicas
Tambien existen funciones básicas al igual que ```head()``` que se puede utilizar para visualizar y manipular los datos como por ejemplo: <br>
```values```: devuelve los valores del dataframe como una matriz (se pueden utilizar las funciones de Numpy). <br>
```drop(nombre,axis)```: Elimina la fila (axis=0) o columna (axis=1) según el nombre especificado. <br>
```sort_values(col)```: Realiza el orden según la columna definida. <br>
```count()```: cuenta los valores presentes diferentes de nulos o NA. <br>
```value_counts()```: cuenta el número de veces que se repiten los valores. <br>

También, si eres lo suficientemente cuidadoso puedes llamar varias funciones de una sola vez para ahorrar lineas de código

In [ ]:
matriz = df.drop(['Unnamed: 0','Species'],axis=1).values

matriz.mean(axis=0)

Para llamar a las columnas del DataFrame, se puede utilizar como si el elemento de pandas se comportara como un diccionario. Es decir, puedes llamar la información (o Serie) de una columna del Dataframe a través del código ```dataframe['nombre_columna']```

In [ ]:
display(df.count())
df['Species'].value_counts()

### Ejercicio #5
Con el DataFrame *iris* cargado anteriormente, muestre el porcentaje de cada uno de los valores presentes en una columna específica. Por ejemplo:
```python
df['Sepal.Width']

3.0    17.333333
2.8     9.333333
3.2     8.666667
3.4     8.000000
3.1     7.333333
2.9     6.666667
2.7     6.000000
2.5     5.333333
3.5     4.000000
3.8     4.000000
3.3     4.000000
2.6     3.333333
2.3     2.666667
3.6     2.666667
2.4     2.000000
2.2     2.000000
3.7     2.000000
3.9     1.333333
4.2     0.666667
4.1     0.666667
4.4     0.666667
2.0     0.666667
4.0     0.666667
```

### Ejercicio #6
Con el DataFrame *iris* cargado anteriormente, establezca una función que le permita definir los valores de un intervalo de confianza de probabilidad definida por un parámetro. Por ejemplo:
```python
intConfianza(0.05)
        Unnamed: 0	Sepal.Length	Sepal.Width	  Petal.Length	Petal.Width
0.025	     4.725	      4.4725	     2.2725	        1.2725	        0.1
0.975	   146.275	      7.7000	     3.9275	        6.4550	        2.4
```
- **Nota:** Recuerde que un intervalo de confianza de $\alpha$ está definido como el cuantil de los datos en $\alpha/2$ y $1-\alpha/2$